Repository TS-Rogue-Star/Rogue-Star, pull requests merged in 2024-12, with the labels that each got.

#683 Shadekin Light Flicker adjustments
  code/game/objects/items/devices/flashlight.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
  code/modules/mob/living/living_rs.dm
  code/modules/power/lighting.dm
  vorestation.dme
Labels: enhancement

#684 Fixes bones
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/organ_external.dm
Labels: bug

#688 Makes miners spawn with mining voucher. Fixes them. Expands the list.
  code/datums/outfits/jobs/cargo.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Labels: enhancement

#708 Borg Icon Optimization and Weapon Modulation
  code/__defines/borg_overlays.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot_modules/event.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/swarm.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/mob/living/silicon/robot/sprites/_sprite_datum.dm
  code/modules/mob/living/silicon/robot/sprites/combat.dm
  code/modules/mob/living/silicon/robot/sprites/event.dm
  code/modules/mob/living/silicon/robot/sprites/fluff.dm
  code/modules/mob/living/silicon/robot/sprites/science.dm
  code/modules/mob/living/silicon/robot/sprites/security.dm
  code/modules/projectiles/guns/energy/cyborg.dm
  vorestation.dme
Labels: bug

#709 Makes unabsorb chem not give you INFINITE hallucinations!
  code/modules/reagents/reagents/vore_vr.dm
Labels: bug

#714 Borg Multibelly, Glowing stomachs.
  code/game/Rogue Star/cyborgs/example/borg_example.dm
  code/game/Rogue Star/cyborgs/example/borg_example.dmi
  code/modules/mob/living/carbon/human/human_rs.dm
  code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
  code/modules/mob/living/carbon/human/update_icons_rs.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/sprites/_sprite_datum.dm
  code/modules/mob/living/simple_mob/simple_mob_vr.dm
  code/modules/mob/living/simple_mob/subtypes/vore/vore.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/living_ch.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/mob_vr.dm
  code/modules/vore/eating/vore_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  code/modules/vore/mouseray.dm
  tgui/packages/tgui/interfaces/VorePanel.js
Labels: bug, enhancement

#715 Makes bodyscanners use the proper move proc
  code/game/machinery/adv_med.dm
Labels: bug

#716 Makes firefighter hats not useless in fires
  code/modules/clothing/head/hardhat.dm
Labels: bug
